module.exports = {
  tours: [
        {
      _id: '1',
      name: 'Discover the historic center',
      location: "CDMX",
      category: 'Culture',
      image: 'https://c0.wallpaperflare.com/preview/371/682/395/mexico-ciudad-de-mexico-palacio-de-bellas-artes-city.jpg',
      price: "500 mxn/pp",
      brand: '-',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      about : "Get to know the history of many of the most famous places such as the Palacio de Bellas Artes, Zocalo, Chinatown, and the cathedral, but we will also visit less touristy spots like old colonial houses and traditional candy stores, and get to know traditions that are still alive today. Plus, a perfect snack-stop and many, many fun facts."
    },
    {
      _id: '2',
      name: 'Chichen Itza, Cenote and Valladolid',
      location: "Riviera Maya",
      category: 'Culture',
      image: 'https://www.mexicodesconocido.com.mx/wp-content/uploads/2010/05/chichen-itza-arquitectura-que-visitar.png',
      price: "1,190 mxn pp"
      ,
      brand: '-',
      rating: 5,
      numReviews: 51,
      about : "I will take you to explore one of the seven wonders of the modern world Chichen Itza in a unique experience. Before we will pass to the center of Valladolid and after knowing the archeological site I will take you to know an authentic Mayan cenote, beauty of nature full of mysticism. At noon you will enjoy a delicious buffet of regional Mexican food with vegetarian options. /n   Once in Chichen Itza, we will walk through the observatory, the Temple of the Warriors and the Ball Court. And you will see the legendary Kukulkan Pyramid, also known as El Castillo, from the front, and I will tell you how during the equinox on a clear day, a snake slides down the stairs of the pyramid, which is actually a shadow created by the setting sun . You will live closely the mysteries of acoustics in its architecture, which to date are not fully understood. You will clearly hear a whisper 159 feet (46 meters) away on one of the platforms on the colossal ball court where the Maya played sports. /n With this exclusive tour, your visit to Chichen Itza allows you to explore the archeological site in an exclusive and unique way!"
    },
    {
      _id: '3',
      name: 'Magic CENOTES + Hacienda',
      location: "Riviera Maya",
      category: 'Recreative',
      image: 'https://aquaworld.com.mx/wp-content/uploads/2021/04/que-son-los-cenotes_1100x619.jpg',
      price: "990 mxn pp",
      brand: '-',
      rating: 4,
      numReviews: 45,
      about : "This is an authentic Yucatecan experience. We'll visit 2 of our favorite cenotes and one hacienda (historical building) on ​​this day of Mayan jungle adventure & probably (hopefully) we'll have them just to ourselves (depending on the season and the day) or at least we won't find a crowd in them. (Perfect for families, couples, groups of friends, and solo travelers). The first cenote is a cavern one, with sapphire blue water (not cold) from where we will appreciate to the bottom of it (it may vary in raining season). The second cenote is a perfectly shaped open circle with incredible emerald water surrounded by trees and birds.       We’ll tell you a few things about the mayan culture as you take in the impressive views of these hundreds of millions of year old rock formation while you swim, snorkel, explore, float, do high jumps from almost 32 ft! (just for the most adventurous) or just relax in each of these cold&fresh water cenotes taking pictures. We will stay from 45 mins to 1 hour (depending on you) in each cenote, without rushing (something typical in normal tours).        Finally, you will enjoy a regional artisanal organic firewood cooked meal prepared by the Mayan community from the harvest to your plate (welcome to México!) for less than the cost of a beer in california! (Not included in the price)"
    },
    {
      _id: '4',
      name: 'Mezcal tasting & dinner in mini jungle',
      location: 'Riviera Maya',
      category: 'Nightlife',
      image: "https://media-cdn.tripadvisor.com/media/photo-s/07/81/72/67/kanha-jungle-lodge.jpg",
      brand: '-',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Knowing Tlaquepaque',
      location: 'Jalisco',
      category: 'Culture',
      image: 'https://heraldodemexico.com.mx/u/fotografias/m/2021/6/17/f608x342-385637_415360_0.jpg',
      price: "900 mxn pp",
      brand: '-',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
      about :"Join us for an intimate dinner party & mezcal tasting in our private jungle garden in the center of Tulum Pueblo! Everyone is welcome to our garden where we will prepare a 3-course dinner cooked on the fire paired with 1.5 ounce tastings of five artisanal, small-batch mezcals sourced from different regions around the country. We create a new dinner menu for every tasting based on any allergies or dietary restrictions. This experience is best for adventurous eaters as we do not disclose the menu beforehand. For an idea of what we typically serve, refer to our photos! Throughout the dinner, we will talk a little bit about the differences between mezcal and tequila, the process of producing mezcal, what to look for when purchasing mezcal & why it has become so popular in the past few years. Most importantly, we’ll have a good time sharing food & drinks, and creating new experiences with great people."
    },
    {
      _id: '6',
      name: 'Visiting the “9 esquinas',
      location: 'Jalisco',
      category: 'Gastronomic',
      image: 'https://guadalajaramidestino.com/wp-content/uploads/2018/04/Main-Birrieria-9-esquinas.jpg',
      price: "600 mxn pp",
      brand: '-',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
  ],
};
